config/routes.rb
Betafisha::Application.routes.draw do

  devise_for :users
  resources :users
  resources :posts
  resources :topics
  resources :forums
  resources :events
  resources :coupons
  resources :news_blocks
  resources :news_posts
  resources :page_subjects


  resources :sports
  resources :countries
  resources :leagues
  resources :participants


  # nav
  get "site_top_navigation/coefficients"
  match "coefficients" =>  "site_top_navigation#coefficients", :as => :coefficients
  get "site_top_navigation/bookmakers"
  match "bookmakers"  =>  "site_top_navigation#bookmakers", :as => :bookmakers
  get "site_top_navigation/statistics"
  match "statistics" =>  "site_top_navigation#statistics", :as => :statistics
  get "site_top_navigation/tools"
  match "tools" =>  "site_top_navigation#tools", :as => :tools

 # add coupon
  match "leaguetocoupon", :to =>  "leagues#leaguetocoupon", :as => :leaguetocoupon

  # admin
  get "admin/users_manager"
  match "admin" =>  "admin#users_manager", :as => :admin

  get "admin/leagues_manager"
  match "admin/leagues_manager" =>  "admin#leagues_manager", :as => :leagues_manager

  get "admin/users_manager"
  match "admin/users_manager" =>  "admin#users_manager", :as => :users_manager

  get "admin/pages_manager"
  match "admin/pages_manager" =>  "admin#pages_manager", :as => :pages_manager

  get "admin/news_manager"
  match "admin/news_manager" =>  "admin#news_manager", :as => :news_manager

  get "admin/bookmakers_manager"
  match "admin/bookmakers_manager" =>  "admin#bookmakers_manager", :as => :bookmakers_manager

  get "admin/add_bookmaker_relation"
  match "admin/add_bookmaker_relation" =>  "admin#add_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/delete_bookmaker_relation"
  match "admin/delete_bookmaker_relation" =>  "admin#delete_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/cache_expire"
  match "admin" =>  "admin#cache_expire", :as => :cache_expire

  post "admin/league_edit"
  post "admin/league_new"

  post "admin/sport_edit"
  post "admin/sport_new"

  post "admin/country_edit"
  post "admin/country_new"

  #devise





  # statc (flat) pages
  resources :pages
  match '/info/:permalink' => "pages#show"

  # root page
  root :to => "site_top_navigation#coefficients"

end


app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :topics, :dependent => :destroy

  default_scope :order => 'forums.created_at DESC'
end

app/controllers/forums_controller.rb
# coding: utf-8
class ForumsController < ApplicationController

  before_filter :authenticate, :except => [:index, :show]

  #uses_tiny_mce

  layout 'forum'

  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(params[:forum])
    if @forum.save
      redirect_to forums_path, :notice => "Successfully created forum."
    else
      render 'new'
    end
  end

  def edit
    @forum = Forum.find(params[:id])
  end

  def update
    @forum = Forum.find(params[:id])
    if @forum.update_attributes(params[:forum])
      redirect_to forums_path, :notice  => "Successfully updated forum."
    else
      render 'edit'
    end
  end

  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    redirect_to forums_path, :notice => "Successfully destroyed forum."
  end


end

app/views/forums/_form.html.erb
<%= form_for @forum do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit "Сохранить" %></p>
<% end %>

app/views/forums/edit.html.erb
<% title "Edit Forum" %>
<%= render 'form' %>

app/views/forums/index.html.erb
<% title "Форумы" %>

<table>
  <tr>
    <th class="forum-name">Форум</th>
    <th class="forum-description">Описание</th>
    <th class="forum-updated">Последние обновление</th>
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <th class="forum-admin"></th>
      <% end %>
    <% end %>
  </tr>
    <% for forum in @forums %>
      <tr>
        <td class="forum-name"><%= link_to forum.name, forum %> (<%= forum.topics.count %>)</td>
        <td class="forum-description"><%= forum.description %></td>
        <% if !forum.topics.empty? %>
           <td class="forum-updated"><%= forum.topics.last.created_at > 1.days.ago ? image_tag("http://www.awwwards.com/images/ico_pending.png") + " " + time_ago_in_words(forum.topics.last.created_at) + t( :ago ) : l(forum.topics.last.created_at, :format => :long) if !forum.topics.last.nil? %> </td>
        <% else %>
           <td class="forum-updated"> нет постов </td>
        <% end %>
        <% if user_signed_in?%>
          <% if current_user.admin? %>
            <td class="forum-admin"><%= link_to "Редактировать", edit_forum_path(forum), :class => "forum-edit-icon" %> <%= link_to "Удалить", forum, :confirm => 'Вы уверены, что хотите удалить форум?', :class => "forum-delete-icon", :method => :delete %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
</table>
<% if user_signed_in?%>
  <% if current_user.admin? %>
    <p><%= link_to "Добавить форум", new_forum_path, :class => "forum-add-btn" %></p>
  <% end %>
<% end %>

app/views/forums/new.html.erb
<% title "New Forum" %>

<%= render 'form' %>

<p><%= link_to "Back to List", forums_path %></p>

app/views/forums/show.html.erb
<% title "Форум" %>

<div class="topic-header">
  <%= link_to "Форумы", forums_path %> »  <%= @forum.name %>
  <%#= @forum.description %>
</div>


<table>
  <tr>
    <th class="topic-name">Топики</th>
    <th>Ответов</th>
    <th>Автор</th>
    <th>Последние обновление</th>
    <% if user_signed_in?%>
      <% if current_user.admin? %>
        <th class="topic-admin"></th>
      <% end %>
    <% end %>
  </tr>
    <% for topic in @forum.topics %>
      <tr>
        <td class="topic-name"> <%= link_to topic.name, topic %> </td>
        <td> <%= topic.posts.count %> </td>
        <td> <%= topic.user.username %> </td>
        <% if !topic.posts.empty? %>
          <td> <%= topic.posts.last.created_at > 1.days.ago ? image_tag("http://www.awwwards.com/images/ico_pending.png") + " " + time_ago_in_words(topic.posts.last.created_at) + t( :ago ) : l(topic.posts.last.created_at, :format => :long) if !topic.posts.last.nil? %> </td>
        <% else %>
           <td> нет комментариев </td>
        <% end %>
        <% if user_signed_in?%>
          <% if current_user.admin? %>
            <td class="topic-admin">  <%= link_to "Редактировать", edit_topic_path(topic), :class => "forum-edit-icon" %><%= link_to "Удалить", topic, :confirm => 'Are you sure?', :class => "forum-delete-icon", :method => :delete %> </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
</table>
<% if user_signed_in?%>
<%# if current_user.topics.first.created_at < 30.minutes.ago %>
  <p><%= link_to "Добавить топик", new_topic_path( :forum => @forum.id ), :class => "forum-add-btn" %></p>
<% end %>
<%# else %>
  <!--p> Вы можете создавать новые топики только один раз в 30 минут.</p-->
<%# end %>

<p><%#= link_to "К форумам", forums_path %></p>