config/routes.rb
Betafisha::Application.routes.draw do

  devise_for :users
  resources :users
  resources :posts
  resources :topics
  resources :forums
  resources :events
  resources :coupons
  resources :news_blocks
  resources :news_posts
  resources :page_subjects


  resources :sports
  resources :countries
  resources :leagues
  resources :participants


  # nav
  get "site_top_navigation/coefficients"
  match "coefficients" =>  "site_top_navigation#coefficients", :as => :coefficients
  get "site_top_navigation/bookmakers"
  match "bookmakers"  =>  "site_top_navigation#bookmakers", :as => :bookmakers
  get "site_top_navigation/statistics"
  match "statistics" =>  "site_top_navigation#statistics", :as => :statistics
  get "site_top_navigation/tools"
  match "tools" =>  "site_top_navigation#tools", :as => :tools

 # add coupon
  match "leaguetocoupon", :to =>  "leagues#leaguetocoupon", :as => :leaguetocoupon

  # admin
  get "admin/users_manager"
  match "admin" =>  "admin#users_manager", :as => :admin

  get "admin/leagues_manager"
  match "admin/leagues_manager" =>  "admin#leagues_manager", :as => :leagues_manager

  get "admin/users_manager"
  match "admin/users_manager" =>  "admin#users_manager", :as => :users_manager

  get "admin/pages_manager"
  match "admin/pages_manager" =>  "admin#pages_manager", :as => :pages_manager

  get "admin/news_manager"
  match "admin/news_manager" =>  "admin#news_manager", :as => :news_manager

  get "admin/bookmakers_manager"
  match "admin/bookmakers_manager" =>  "admin#bookmakers_manager", :as => :bookmakers_manager

  get "admin/add_bookmaker_relation"
  match "admin/add_bookmaker_relation" =>  "admin#add_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/delete_bookmaker_relation"
  match "admin/delete_bookmaker_relation" =>  "admin#delete_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/cache_expire"
  match "admin" =>  "admin#cache_expire", :as => :cache_expire

  post "admin/league_edit"
  post "admin/league_new"

  post "admin/sport_edit"
  post "admin/sport_new"

  post "admin/country_edit"
  post "admin/country_new"

  #devise





  # statc (flat) pages
  resources :pages
  match '/info/:permalink' => "pages#show"

  # root page
  root :to => "site_top_navigation#coefficients"

end


app/models/topic.rb
class Topic < ActiveRecord::Base

  attr_accessible :name, :content
  belongs_to :forum
  belongs_to :user
  has_many :posts, :dependent => :destroy

  default_scope :order => 'topics.created_at DESC'

end

app/controllers/topics_controller.rb
# coding: utf-8
class TopicsController < ApplicationController

  before_filter :authenticate

  layout 'forum'

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(params[:topic])
    @topic.forum = Forum.find(params[:topic][:forum_id])

    if @topic.save
      redirect_to @topic.forum, :notice => "Successfully created topic."
    else
      render 'new'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
      redirect_to @topic, :notice  => "Successfully updated topic."
    else
      render 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_url, :notice => "Successfully destroyed topic."
  end

end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <%= f.error_messages %>
  <% if params[:forum] %> <input type="hidden" id="topic_forum_id" name="topic[forum_id]" value="<%= params[:forum] %>" /> <% end %>

   <p>
    <%= f.label :name, "Название топика" %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :content, "Первый пост" %><br />
    <%= f.text_area :content %>
  </p>

  <p><%= f.submit "Сохранить" %></p>
<% end %>

app/views/topics/edit.html.erb
<% title "Edit Topic" %>

<%= render 'form' %>

app/views/topics/index.html.erb
<% title "Topics" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for topic in @topics %>
    <tr>
      <td><%= topic.name %></td>
      <td><%= link_to "Show", topic %></td>
      <td><%= link_to "Edit", edit_topic_path(topic) %></td>
      <td><%= link_to "Destroy", topic, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Topic", new_topic_path %></p>

app/views/topics/new.html.erb
<% title "New Topic" %>

<%= render 'form' %>

<p><%= link_to "Back to List", topics_path %></p>

app/views/topics/show.html.erb
<% title "Топик" %>

<div class="topic-header">
  <%= link_to "Форумы", forums_path %> » <%= link_to @topic.forum.name, @topic.forum %> »  <%= @topic.name %>
</div>

<div class="post first-post">

  <div class="post-user">
   <p> <%= @topic.user.username %> </p>
   <p> <%= @topic.created_at > 1.days.ago ? image_tag("http://www.awwwards.com/images/ico_pending.png") + " " + time_ago_in_words(@topic.created_at) + t( :ago ) : l(@topic.created_at, :format => :long) if !@topic.nil? %> </p>
  <% if current_user.admin? %>
   <p> <%= link_to "Редактировать", edit_topic_path(@topic), :class => "forum-edit-icon" %> <%= link_to "Удалить", @topic, :confirm => 'Are you sure?', :class => "forum-delete-icon", :method => :delete %> </p>
  <% end %>
  </div>

  <div class="post-content"> <%= @topic.content %> </div>
</div>

<% for post in @topic.posts %>
  <div class="post">
    <div class="post-user">
       <p> <%= post.user.username %> </p>
       <p> <div class="post-info"> <%= post.created_at > 1.days.ago ? image_tag("http://www.awwwards.com/images/ico_pending.png") + " " + time_ago_in_words(post.created_at) + t( :ago ) : l(post.created_at, :format => :long) if !post.nil? %> </div> </p>
       <% if current_user.admin? %>
        <p> <%= link_to "Редактировать", edit_post_path(post), :class => "forum-edit-icon" %> <%= link_to "Удалить", post, :confirm => 'Are you sure?', :class => "forum-delete-icon", :method => :delete %> </p>
       <% end %>
    </div>
    <div class="post-content"> <%= post.content %> </div>
  </div>

<% end %>
<% if user_signed_in?%>
  <p><%= link_to "Добавить пост", new_post_path( :topic => @topic.id ), :class => "forum-add-btn"  %></p>
<% end %>