config/routes.rb
Betafisha::Application.routes.draw do

  devise_for :users
  resources :users
  resources :posts
  resources :topics
  resources :forums
  resources :events
  resources :coupons
  resources :news_blocks
  resources :news_posts
  resources :page_subjects


  resources :sports
  resources :countries
  resources :leagues
  resources :participants


  # nav
  get "site_top_navigation/coefficients"
  match "coefficients" =>  "site_top_navigation#coefficients", :as => :coefficients
  get "site_top_navigation/bookmakers"
  match "bookmakers"  =>  "site_top_navigation#bookmakers", :as => :bookmakers
  get "site_top_navigation/statistics"
  match "statistics" =>  "site_top_navigation#statistics", :as => :statistics
  get "site_top_navigation/tools"
  match "tools" =>  "site_top_navigation#tools", :as => :tools

 # add coupon
  match "leaguetocoupon", :to =>  "leagues#leaguetocoupon", :as => :leaguetocoupon

  # admin
  get "admin/users_manager"
  match "admin" =>  "admin#users_manager", :as => :admin

  get "admin/leagues_manager"
  match "admin/leagues_manager" =>  "admin#leagues_manager", :as => :leagues_manager

  get "admin/users_manager"
  match "admin/users_manager" =>  "admin#users_manager", :as => :users_manager

  get "admin/pages_manager"
  match "admin/pages_manager" =>  "admin#pages_manager", :as => :pages_manager

  get "admin/news_manager"
  match "admin/news_manager" =>  "admin#news_manager", :as => :news_manager

  get "admin/bookmakers_manager"
  match "admin/bookmakers_manager" =>  "admin#bookmakers_manager", :as => :bookmakers_manager

  get "admin/add_bookmaker_relation"
  match "admin/add_bookmaker_relation" =>  "admin#add_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/delete_bookmaker_relation"
  match "admin/delete_bookmaker_relation" =>  "admin#delete_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/cache_expire"
  match "admin" =>  "admin#cache_expire", :as => :cache_expire

  post "admin/league_edit"
  post "admin/league_new"

  post "admin/sport_edit"
  post "admin/sport_new"

  post "admin/country_edit"
  post "admin/country_new"

  #devise





  # statc (flat) pages
  resources :pages
  match '/info/:permalink' => "pages#show"

  # root page
  root :to => "site_top_navigation#coefficients"

end


app/views/admin/_bookmakers_form.html.erb
<%= form_for( :admin, :url => { :action =>"add_bookmaker_relation", :controller => "admin"}, :html => { :class => "bookmakers_form" }) do |f| %>
  <% flash.each do |key, value| %>
	  <div class="flash <%= key %>"> <%= value %> </div>
  <% end %>
  <div class="field">
    <b> Фильтры: </b> <br/>
    <%= f.label :table_name, "Таблицы:" %> <br/>
    <%= f.select :table_name,
    	options_for_select( ["country", "league"], @params[:table_name] ),
    	:multiple => false
    %>
  </div>
  <div class="field">
  	<%= f.label :bookmaker_name, "Букмекеры:" %> <br/>
    <%= f.select :bookmaker_name,
    	options_for_select( @bookmakers.collect { |p| [p.name] }, @params[:bookmaker_name]),
    	:multiple => false, :class => "bookmaker_select"
    %> <br/>
  </div>
  <div class="field">
  <b> Выберите элементы для связи:   </b> <br/>
  	<%= f.label :common_element_id, "Наши значения" %> <br/>
  	<%= f.text_field :common_element_id ,{ :data => { :autocomplete_source => bookmakers_manager_path}, :placeholder => "введите наше значение...", :value => @common_item } %>
   	<p>
  </div>
  <% if !@values.nil? %>
	  <div class="field">
	  <%= f.label :bookmaker_element_id, "Значения для " + @params[:bookmaker_name] %><br/>
	  <%= f.text_field :bookmaker_element_id ,{ :data => { :autocomplete_source => bookmakers_manager_path }, :placeholder => "введите значение букмекера...", :value => @bookmaker_item }%>
	  </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Объединить" %>
  </div>
<% end %>
<% if !@elements.nil? %>
  <ul>
    <b>Существующие связи:</b>
    <% @elements.each do |element| %>
    <li><span id="has_relation">  <%= element.element_name %> </span> <%= link_to "Удалить связь", "#", :class => "delete_relation", :id => element.id, :data => element.element_name    %> </li>
    <% end %>
  </ul>
<% end %>
<%= javascript_include_tag 'forms' %>

app/views/admin/bookmakers_manager.js.erb
$(".tab_content").html(' <%= escape_javascript ( render 'bookmakers_form' ) %>  ');

app/views/admin/cache_expire.js.erb
 $("div.accordian").html('<div class="form_name grid_5">Предпросмотр</div> <%= escape_javascript ( render  'sports/sports_content'  ) %>  ');

app/views/admin/country_new.js.erb
$("div.add_edit_form").html(' <%= escape_javascript ( render 'countries/new_country_form' ) %>  ');

app/views/admin/index.html.erb
<ul class="tabs">
	<li><%= link_to "Пользователи", admin_users_manager_path, :class => 'users_manager_tab' %></li>
	<li><%= link_to "Лиги", admin_leagues_manager_path, :class => 'leagues_manager_tab' %></li>
	<li><%= link_to "Страницы", admin_pages_manager_path, :class => 'pages_manager_tab' %></li>
	<li><%= link_to "Букмекеры", admin_bookmakers_manager_path, :class => 'bookmakers_manager_tab' %></li>
</ul>
<div class="tab_container">
	Lorem ipsum dolor sit amet, consectetur adipisicing elit,
	sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
	Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
	nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
	reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
	Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
	officia deserunt mollit anim id est laborum.
</div>

app/views/admin/league_new.js.erb
$("div.add_edit_form").html(' <%= escape_javascript ( render 'leagues/new_league_form' ) %>  ');

app/views/admin/leagues_manager.html.erb
 <ul class="tabs">
    <!--li><%#= link_to "Приложение", admin_path , :class => 'admin_profile_tab' %></li-->
    <li><%= link_to "Пользователи", admin_users_manager_path, :class => 'users_manager_tab' %></li>
    <li class="active"><%= link_to "Лиги", admin_leagues_manager_path, :class => 'leagues_manager_tab' %></li>
    <li><%= link_to "Страницы", admin_pages_manager_path, :class => 'pages_manager_tab' %></li>
    <li><%= link_to "Букмекеры", admin_bookmakers_manager_path, :class => 'bookmakers_manager_tab' %></li>
</ul>
<div class="tab_container">
    <div class="tab_content">
      <div class="accordian grid_5">
        <div class="form_name grid_5">
        Предпросмотр
        </div>
        <%= render 'sports/sports_content' %>
      </div>
      <div class="add_edit_form grid_9">
        <%= render 'leagues/new_league_form' %>
      </div>
    <div class="grid_5">
      - <b> Управление лигами </b><br />
        <p><%= link_to "Сбросить кеш!", "#", :id => "cache-expire-button"%> </p>
      <br />
  </div>
</div>

app/views/admin/news_manager.html.erb
<ul class="tabs">
  <!--li><%#= link_to "Приложение", admin_path , :class => 'admin_profile_tab' %></li-->
  <li><%= link_to "Пользователи", admin_users_manager_path, :class => 'users_manager_tab' %></li>
  <li><%= link_to "Лиги", admin_leagues_manager_path, :class => 'leagues_manager_tab' %></li>
  <li><%= link_to "Страницы", admin_pages_manager_path, :class => 'pages_manager_tab' %></li>
  <li><%= link_to "Букмекеры", admin_bookmakers_manager_path, :class => 'bookmakers_manager_tab' %></li>
</ul>
<div class="tab_container">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit,
  sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
  nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
  reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
  officia deserunt mollit anim id est laborum.
</div>

app/views/admin/pages_manager.js.erb
$('#pages_manager_show').html('<%= escape_javascript ( render 'pages/page_manager' ) %>');
$('#pages_manager_add').html('<%= escape_javascript ( render 'pages/form' ) %>');

app/views/admin/sport_edit.js.erb
$("div.add_edit_form").html(' <%= escape_javascript ( render 'sports/edit_sport_form' ) %>  ');

app/views/admin/sport_new.js.erb
$("div.add_edit_form").html(' <%= escape_javascript ( render 'sports/new_sport_form' ) %>  ');

app/views/admin/sports_manager.html.erb
<ul class="tabs">
  <li><%= link_to "Настройки приложения", admin_path , :class => 'admin_profile_tab' %></li>
  <li><%= link_to "Управление пользователями", admin_users_manager_path, :class => 'users_manager_tab' %></li>
  <li class="active"><%= link_to "Управление лигами", admin_sports_manager_path, :class => 'sports_manager_tab' %></li>
</ul>
<div class="tab_container">
    <div class="tab_content">
        <div class="accordian grid_5"">
          <div class="form_name grid_5">
          Предпросмотр
          </div>
          <%= render 'sports/sports_content' %>
        </div>
    <div class="add_edit_form grid_9">
      <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <%= render 'leagues/new_league_form' %>
    </div>
    <div class="grid_4">
      - <b> Управление лигами </b><br />
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      <br />
      - <b> Подсказки </b><br />
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>
    </div>
</div>

app/views/admin/users_manager.html.erb
<ul class="tabs">
  <!--li><%#= link_to "Приложение", admin_path , :class => 'admin_profile_tab' %></li-->
  <li class="active"><%= link_to "Пользователи", admin_users_manager_path, :class => 'users_manager_tab' %></li>
  <li><%= link_to "Лиги", admin_leagues_manager_path, :class => 'leagues_manager_tab' %></li>
  <li><%= link_to "Страницы", admin_pages_manager_path, :class => 'pages_manager_tab' %></li>
  <li><%= link_to "Букмекеры", admin_bookmakers_manager_path, :class => 'bookmakers_manager_tab' %></li>
</ul>
<div class="tab_container">
  <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
  <% end %>
    <%= render 'users/user_manager' %>
</div>

app/views/admin/users_manager.js.erb
$('.tab_container').html('<%= escape_javascript ( render 'users/user_manager' ) %>');