config/routes.rb
Betafisha::Application.routes.draw do

  devise_for :users
  resources :users
  resources :posts
  resources :topics
  resources :forums
  resources :events
  resources :coupons
  resources :news_blocks
  resources :news_posts
  resources :page_subjects


  resources :sports
  resources :countries
  resources :leagues
  resources :participants


  # nav
  get "site_top_navigation/coefficients"
  match "coefficients" =>  "site_top_navigation#coefficients", :as => :coefficients
  get "site_top_navigation/bookmakers"
  match "bookmakers"  =>  "site_top_navigation#bookmakers", :as => :bookmakers
  get "site_top_navigation/statistics"
  match "statistics" =>  "site_top_navigation#statistics", :as => :statistics
  get "site_top_navigation/tools"
  match "tools" =>  "site_top_navigation#tools", :as => :tools

 # add coupon
  match "leaguetocoupon", :to =>  "leagues#leaguetocoupon", :as => :leaguetocoupon

  # admin
  get "admin/users_manager"
  match "admin" =>  "admin#users_manager", :as => :admin

  get "admin/leagues_manager"
  match "admin/leagues_manager" =>  "admin#leagues_manager", :as => :leagues_manager

  get "admin/users_manager"
  match "admin/users_manager" =>  "admin#users_manager", :as => :users_manager

  get "admin/pages_manager"
  match "admin/pages_manager" =>  "admin#pages_manager", :as => :pages_manager

  get "admin/news_manager"
  match "admin/news_manager" =>  "admin#news_manager", :as => :news_manager

  get "admin/bookmakers_manager"
  match "admin/bookmakers_manager" =>  "admin#bookmakers_manager", :as => :bookmakers_manager

  get "admin/add_bookmaker_relation"
  match "admin/add_bookmaker_relation" =>  "admin#add_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/delete_bookmaker_relation"
  match "admin/delete_bookmaker_relation" =>  "admin#delete_bookmaker_relation", :as => :add_bookmaker_relation

  get "admin/cache_expire"
  match "admin" =>  "admin#cache_expire", :as => :cache_expire

  post "admin/league_edit"
  post "admin/league_new"

  post "admin/sport_edit"
  post "admin/sport_new"

  post "admin/country_edit"
  post "admin/country_new"

  #devise





  # statc (flat) pages
  resources :pages
  match '/info/:permalink' => "pages#show"

  # root page
  root :to => "site_top_navigation#coefficients"

end


app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :name, :priority, :league_id

  belongs_to :league
  has_many :participants

  has_many :bets, :dependent => :destroy

  def self.with_bet_type (bet_type, l_id)
    find_by_sql [("SELECT e.* FROM events e INNER JOIN leagues l ON l.id = e.league_id INNER JOIN bets b ON e.id = b.event_id INNER JOIN bet_types bt ON b.bet_type_id = bt.id WHERE bt.name = ? and l.id = ? GROUP BY e.name"), bet_type, l_id]
  end

#def self.find_by_first_letter(letter = "A")
 #     find_by_sql ["select * from artists where ucase(left(artist_name, 1)) = ?", letter]
 #  end
  #scope :to_win_with_draw, with_bet_type("1x2")    #joins(:bets) & Bet.to_win_with_draw

  #find old elements, interval can be changed
  scope :older_than, lambda { |time| where("updated_at < ?", time) }

end

#SELECT * FROM events e INNER JOIN bets b ON e.id = b.event_id INNER JOIN bet_types bt ON b.bet_type_id = bt.id WHERE bt.name = '1x2'

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate, :only => [:edit, :update, :destroy]
  before_filter :admin_user, :only => [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to @event, :notice => "Successfully created event."
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to @event, :notice  => "Successfully updated event."
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, :notice => "Successfully destroyed event."
  end
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </p>
  <p>
    <%= f.label :league_id %><br />
    <%= f.text_field :league_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/events/_outright.html.erb
<% content_for :content do %>
  <% @event.bets.each do |b| %>
    <% if b.bet_type.name == 'Outright'%>
      <div class="event">
        <div class="bet-name">
          <%= b.name %>
        </div>
        <div class="bet-odd">
        <%= b.odd %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/events/_towin.html.erb
<%= "ставок нет" if @event.bets.to_win.empty? %>
<%  @event.bets.to_win.each_with_index do |b,i| %>
  <% if i%2 == 0 and i > 0 %>
    <br />
    <br />
  <% end %>
  <% if i == 0 %>
    <div class = "odd-bookmaker-header">Букмекер</div>
    <div class = "odd-value">1</div>
    <div class = "odd-value">2</div>
    <br />
    <br />
  <% end %>
  <% if i%2 == 0 %>
    <div class="odd-bookmaker-header"><%= image_tag imageUriByBookmakerName( b.bookmaker.name ), :width => 100, :height => 20 %></div>
  <% end %>
    <div class="odd-value"><%=b["odd"] %></div>
<% end %>

app/views/events/_towin_with_draw.html.erb
<%= "ставок нет" if @event.bets.to_win_with_draw.empty? %>
<%  @event.bets.to_win_with_draw.each_with_index do |b,i| %>
  <% if i%3 == 0 and i > 0 %>
    <br />
    <br />
  <% end %>
  <% if i == 0 %>
    <div class = "odd-bookmaker-header">Букмекер</div>
    <div class = "odd-value">1</div>
    <div class = "odd-value">X</div>
    <div class = "odd-value">2</div>
    <br />
    <br />
  <% end %>
  <% if i%3 == 0 %>
    <div class="odd-bookmaker-header"><%= image_tag imageUriByBookmakerName( b.bookmaker.name ), :width => 100, :height => 20 %></div>
  <% end %>
    <div class="odd-value"><%= b["odd"] %></div>
<% end %>

app/views/events/edit.html.erb
<% title "Edit Event" %>
<%= render 'form' %>
<p>
  <%= link_to "Show", @event %> |
  <%= link_to "View All", events_path %>
</p>

app/views/events/index.html.erb
<% title "Events" %>
<table>
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th>Date</th>
    <th>Time</th>
    <th>League</th>
  </tr>
  <% for event in @events %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.priority %></td>
      <td><%= event.date %></td>
      <td><%= event.time %></td>
      <td><%= event.league_id %></td>
      <td><%= link_to "Show", event %></td>
      <td><%= link_to "Edit", edit_event_path(event) %></td>
      <td><%= link_to "Destroy", event, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<p><%= link_to "New Event", new_event_path %></p>

app/views/events/new.html.erb
<% title "New Event" %>
<%= render 'form' %>
<p><%= link_to "Back to List", events_path %></p>

app/views/events/show.html.erb
<% content_for :navigation do %>
  <%= render 'site_top_navigation/main_nav' %>
<% end %>
<% content_for :sub_navigation do %>
  <div id="sub_navigation" class="grid_20">
  <ul>
    <li><%= link_to "Главная", "#" %></li>
    <li><%= link_to "Ближайшие", "#" %></li>
    <li><%= link_to "Live ставки", "#" %></li>
    <li><%= link_to "Топ матчи", "#" %></li>
    <li><%= link_to "Dropping", "#" %></li>
    <li><%= link_to "Вилки", "#" %></li>
    <li><%= link_to "Фильтр", "#" %></li>
  </ul>
  </div>
<% end %>
<% content_for :breadcrumb do %>
   <%= link_to t(:top_menu_coefficients), coefficients_path %>
   »  <%= link_to @event.league.country.name,  @event.league.country %>
   » <%= link_to @event.league.sport.name,  @event.league.sport %>
   » <%= link_to @event.league.name, @event.league %>
   » <%= @event.name %>
<% end %>
<% content_for :left_nav do %>
  <div id="my_coupon">
    <div class="header">Мои Лиги<a id="toggle-coupon-info" href="#" class="active"></a></div>
    <div class="my_coupon_data">
      <%= render 'site_top_navigation/coupons' %>
    </div>
  </div>
  <div id="sports_menu">
    <div class="header">Виды спорта</div>
	  <%= render 'sports/sports_content' %>
	</div>
<% end %>
<% content_for :content do %>
  <div id="refresh_box">
    <ul class="bet-tabs">
        <li><a href="#towin-with-draw">1x2</a></li>
        <li><a href="#to-win">1or2</a></li>
    </ul>
    <div class="tab_container">
        <div id="towin-with-draw" class="tab_content">
          <%= render 'events/towin_with_draw' %>
        </div>
        <div id="to-win" class="tab_content">
          <%= render 'events/towin' %>
        </div>
      </div>
  </div>
<% end %>
<% content_for :right_nav do %>
  <div id="my_coupon">
    <div class="header">Мои Купон<a id="toggle-coupon-clear" href="#" class="active"></a></div>
    <div class="my_coupon_bets">
        <b>Карточка пуста.</b>  <br />
        Добавляйте события, <br />
        кликая на коэффициенты  <br />
        на нашем сайте.  <br />
    </div>
  </div>
<% end %>